// Code generated by MockGen. DO NOT EDIT.
// Source: c:\Users\V14\Downloads\BackendGolangV2024-20240429\repository\interfaces.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateEstate mocks base method.
func (m *MockRepositoryInterface) CreateEstate(ctx context.Context, input CreateEstateInput) (CreateEstateOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEstate", ctx, input)
	ret0, _ := ret[0].(CreateEstateOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEstate indicates an expected call of CreateEstate.
func (mr *MockRepositoryInterfaceMockRecorder) CreateEstate(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEstate", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateEstate), ctx, input)
}

// CreateTree mocks base method.
func (m *MockRepositoryInterface) CreateTree(ctx context.Context, input CreateTreeInput) (CreateTreeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTree", ctx, input)
	ret0, _ := ret[0].(CreateTreeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTree indicates an expected call of CreateTree.
func (mr *MockRepositoryInterfaceMockRecorder) CreateTree(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTree", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateTree), ctx, input)
}

// CreateUser mocks base method.
func (m *MockRepositoryInterface) CreateUser(ctx context.Context, input CreateUserInput) (CreateUserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, input)
	ret0, _ := ret[0].(CreateUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryInterfaceMockRecorder) CreateUser(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateUser), ctx, input)
}

// DeleteUser mocks base method.
func (m *MockRepositoryInterface) DeleteUser(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteUser), ctx, id)
}

// GetEstateById mocks base method.
func (m *MockRepositoryInterface) GetEstateById(ctx context.Context, id string) (Estate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEstateById", ctx, id)
	ret0, _ := ret[0].(Estate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEstateById indicates an expected call of GetEstateById.
func (mr *MockRepositoryInterfaceMockRecorder) GetEstateById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEstateById", reflect.TypeOf((*MockRepositoryInterface)(nil).GetEstateById), ctx, id)
}

// GetEstateStats mocks base method.
func (m *MockRepositoryInterface) GetEstateStats(ctx context.Context, input GetEstateStatsInput) (GetEstateStatsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEstateStats", ctx, input)
	ret0, _ := ret[0].(GetEstateStatsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEstateStats indicates an expected call of GetEstateStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetEstateStats(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEstateStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetEstateStats), ctx, input)
}

// GetTreesByEstateId mocks base method.
func (m *MockRepositoryInterface) GetTreesByEstateId(ctx context.Context, input GetTreesByEstateIdInput) (GetTreesByEstateIdOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTreesByEstateId", ctx, input)
	ret0, _ := ret[0].(GetTreesByEstateIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTreesByEstateId indicates an expected call of GetTreesByEstateId.
func (mr *MockRepositoryInterfaceMockRecorder) GetTreesByEstateId(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTreesByEstateId", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTreesByEstateId), ctx, input)
}

// GetUserByEmail mocks base method.
func (m *MockRepositoryInterface) GetUserByEmail(ctx context.Context, email string) (User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserByEmail), ctx, email)
}

// GetUserById mocks base method.
func (m *MockRepositoryInterface) GetUserById(ctx context.Context, id string) (User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, id)
	ret0, _ := ret[0].(User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserById), ctx, id)
}

// GetUserByUsername mocks base method.
func (m *MockRepositoryInterface) GetUserByUsername(ctx context.Context, username string) (User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserByUsername), ctx, username)
}

// GetUserByUsernameOrEmail mocks base method.
func (m *MockRepositoryInterface) GetUserByUsernameOrEmail(ctx context.Context, input GetUserByUsernameOrEmailInput) (User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsernameOrEmail", ctx, input)
	ret0, _ := ret[0].(User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsernameOrEmail indicates an expected call of GetUserByUsernameOrEmail.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserByUsernameOrEmail(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsernameOrEmail", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserByUsernameOrEmail), ctx, input)
}

// UpdateUser mocks base method.
func (m *MockRepositoryInterface) UpdateUser(ctx context.Context, input UpdateUserInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateUser(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateUser), ctx, input)
}

// CreatePerson mocks base method.
func (m *MockRepositoryInterface) CreatePerson(ctx context.Context, input CreatePersonInput) (CreatePersonOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePerson", ctx, input)
	ret0, _ := ret[0].(CreatePersonOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePerson indicates an expected call of CreatePerson.
func (mr *MockRepositoryInterfaceMockRecorder) CreatePerson(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePerson", reflect.TypeOf((*MockRepositoryInterface)(nil).CreatePerson), ctx, input)
}

// GetPersonByUserId mocks base method.
func (m *MockRepositoryInterface) GetPersonByUserId(ctx context.Context, input GetPersonByUserIdInput) (Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersonByUserId", ctx, input)
	ret0, _ := ret[0].(Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersonByUserId indicates an expected call of GetPersonByUserId.
func (mr *MockRepositoryInterfaceMockRecorder) GetPersonByUserId(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersonByUserId", reflect.TypeOf((*MockRepositoryInterface)(nil).GetPersonByUserId), ctx, input)
}

// UpdatePerson mocks base method.
func (m *MockRepositoryInterface) UpdatePerson(ctx context.Context, input UpdatePersonInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePerson", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePerson indicates an expected call of UpdatePerson.
func (mr *MockRepositoryInterfaceMockRecorder) UpdatePerson(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePerson", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdatePerson), ctx, input)
}

// DeletePerson mocks base method.
func (m *MockRepositoryInterface) DeletePerson(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePerson", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePerson indicates an expected call of DeletePerson.
func (mr *MockRepositoryInterfaceMockRecorder) DeletePerson(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePerson", reflect.TypeOf((*MockRepositoryInterface)(nil).DeletePerson), ctx, id)
}

// CreatePersonEmail mocks base method.
func (m *MockRepositoryInterface) CreatePersonEmail(ctx context.Context, input CreatePersonEmailInput) (CreatePersonEmailOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePersonEmail", ctx, input)
	ret0, _ := ret[0].(CreatePersonEmailOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePersonEmail indicates an expected call of CreatePersonEmail.
func (mr *MockRepositoryInterfaceMockRecorder) CreatePersonEmail(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePersonEmail", reflect.TypeOf((*MockRepositoryInterface)(nil).CreatePersonEmail), ctx, input)
}

// GetPersonEmailsByUserId mocks base method.
func (m *MockRepositoryInterface) GetPersonEmailsByUserId(ctx context.Context, input GetPersonEmailsByUserIdInput) (GetPersonEmailsByUserIdOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersonEmailsByUserId", ctx, input)
	ret0, _ := ret[0].(GetPersonEmailsByUserIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersonEmailsByUserId indicates an expected call of GetPersonEmailsByUserId.
func (mr *MockRepositoryInterfaceMockRecorder) GetPersonEmailsByUserId(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersonEmailsByUserId", reflect.TypeOf((*MockRepositoryInterface)(nil).GetPersonEmailsByUserId), ctx, input)
}

// UpdatePersonEmail mocks base method.
func (m *MockRepositoryInterface) UpdatePersonEmail(ctx context.Context, input UpdatePersonEmailInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePersonEmail", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePersonEmail indicates an expected call of UpdatePersonEmail.
func (mr *MockRepositoryInterfaceMockRecorder) UpdatePersonEmail(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePersonEmail", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdatePersonEmail), ctx, input)
}

// DeletePersonEmail mocks base method.
func (m *MockRepositoryInterface) DeletePersonEmail(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePersonEmail", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePersonEmail indicates an expected call of DeletePersonEmail.
func (mr *MockRepositoryInterfaceMockRecorder) DeletePersonEmail(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePersonEmail", reflect.TypeOf((*MockRepositoryInterface)(nil).DeletePersonEmail), ctx, id)
}

// CreatePersonPhone mocks base method.
func (m *MockRepositoryInterface) CreatePersonPhone(ctx context.Context, input CreatePersonPhoneInput) (CreatePersonPhoneOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePersonPhone", ctx, input)
	ret0, _ := ret[0].(CreatePersonPhoneOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePersonPhone indicates an expected call of CreatePersonPhone.
func (mr *MockRepositoryInterfaceMockRecorder) CreatePersonPhone(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePersonPhone", reflect.TypeOf((*MockRepositoryInterface)(nil).CreatePersonPhone), ctx, input)
}

// GetPersonPhonesByUserId mocks base method.
func (m *MockRepositoryInterface) GetPersonPhonesByUserId(ctx context.Context, input GetPersonPhonesByUserIdInput) (GetPersonPhonesByUserIdOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersonPhonesByUserId", ctx, input)
	ret0, _ := ret[0].(GetPersonPhonesByUserIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersonPhonesByUserId indicates an expected call of GetPersonPhonesByUserId.
func (mr *MockRepositoryInterfaceMockRecorder) GetPersonPhonesByUserId(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersonPhonesByUserId", reflect.TypeOf((*MockRepositoryInterface)(nil).GetPersonPhonesByUserId), ctx, input)
}

// UpdatePersonPhone mocks base method.
func (m *MockRepositoryInterface) UpdatePersonPhone(ctx context.Context, input UpdatePersonPhoneInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePersonPhone", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePersonPhone indicates an expected call of UpdatePersonPhone.
func (mr *MockRepositoryInterfaceMockRecorder) UpdatePersonPhone(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePersonPhone", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdatePersonPhone), ctx, input)
}

// DeletePersonPhone mocks base method.
func (m *MockRepositoryInterface) DeletePersonPhone(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePersonPhone", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePersonPhone indicates an expected call of DeletePersonPhone.
func (mr *MockRepositoryInterfaceMockRecorder) DeletePersonPhone(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePersonPhone", reflect.TypeOf((*MockRepositoryInterface)(nil).DeletePersonPhone), ctx, id)
}

// CreatePersonSocialMedia mocks base method.
func (m *MockRepositoryInterface) CreatePersonSocialMedia(ctx context.Context, input CreatePersonSocialMediaInput) (CreatePersonSocialMediaOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePersonSocialMedia", ctx, input)
	ret0, _ := ret[0].(CreatePersonSocialMediaOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePersonSocialMedia indicates an expected call of CreatePersonSocialMedia.
func (mr *MockRepositoryInterfaceMockRecorder) CreatePersonSocialMedia(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePersonSocialMedia", reflect.TypeOf((*MockRepositoryInterface)(nil).CreatePersonSocialMedia), ctx, input)
}

// GetPersonSocialMediaByUserId mocks base method.
func (m *MockRepositoryInterface) GetPersonSocialMediaByUserId(ctx context.Context, input GetPersonSocialMediaByUserIdInput) (GetPersonSocialMediaByUserIdOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersonSocialMediaByUserId", ctx, input)
	ret0, _ := ret[0].(GetPersonSocialMediaByUserIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersonSocialMediaByUserId indicates an expected call of GetPersonSocialMediaByUserId.
func (mr *MockRepositoryInterfaceMockRecorder) GetPersonSocialMediaByUserId(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersonSocialMediaByUserId", reflect.TypeOf((*MockRepositoryInterface)(nil).GetPersonSocialMediaByUserId), ctx, input)
}

// UpdatePersonSocialMedia mocks base method.
func (m *MockRepositoryInterface) UpdatePersonSocialMedia(ctx context.Context, input UpdatePersonSocialMediaInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePersonSocialMedia", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePersonSocialMedia indicates an expected call of UpdatePersonSocialMedia.
func (mr *MockRepositoryInterfaceMockRecorder) UpdatePersonSocialMedia(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePersonSocialMedia", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdatePersonSocialMedia), ctx, input)
}

// DeletePersonSocialMedia mocks base method.
func (m *MockRepositoryInterface) DeletePersonSocialMedia(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePersonSocialMedia", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePersonSocialMedia indicates an expected call of DeletePersonSocialMedia.
func (mr *MockRepositoryInterfaceMockRecorder) DeletePersonSocialMedia(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePersonSocialMedia", reflect.TypeOf((*MockRepositoryInterface)(nil).DeletePersonSocialMedia), ctx, id)
}
